class ReviewError(Exception): ...


class AIProviderError(ReviewError): ...


class MalformedAIResponseError(ReviewError): ...


class GitHubError(Exception): ...


class InvalidPRUrlError(GitHubError): ...


class GitHubAuthError(GitHubError): ...


class PRNotFoundError(GitHubError): ...


class GitHubRateLimitError(GitHubError): ...
